name: run WhatsApp bot using actions by takimtod
run-name: WhatsApp bot  ⚡
on:
  schedule:
    - cron: "0 */5 * * *"
jobs:
  Learning-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Script action
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createScheduledWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: github.ref,
              schedule: '0 */5 * * *',
              workflow_file: '.github/workflows/run.yml'
            })
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Install dependencies
        run: go build -o main .

      - name: execute js script by takimtod
        run: go run main.go
