name: run WhatsApp bot using actions by KazeDevID
run-name: WhatsApp bot  ⚡
on: [push]
schedule:
    - cron: "0 */5 * * *"
jobs:
  Learning-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Install dependencies
        run: go build -o main .

      - name: execute js script by KazeDevID
        run: go run main.go
